/**
 * Autogenerated by Avro
 * <p>
 * DO NOT EDIT DIRECTLY
 */
package ru.practicum.avro_example;

import org.apache.avro.message.BinaryMessageDecoder;
import org.apache.avro.message.BinaryMessageEncoder;
import org.apache.avro.message.SchemaStore;
import org.apache.avro.specific.SpecificData;

@org.apache.avro.specific.AvroGenerated
public class SpeedEventAvro extends org.apache.avro.specific.SpecificRecordBase implements org.apache.avro.specific.SpecificRecord {
    public static final org.apache.avro.Schema SCHEMA$ = new org.apache.avro.Schema.Parser().parse("{\"type\":\"record\",\"name\":\"SpeedEventAvro\",\"namespace\":\"ru.practicum.avro_example\",\"fields\":[{\"name\":\"speed\",\"type\":\"double\"},{\"name\":\"acceleration\",\"type\":\"double\"}]}");
    private static final long serialVersionUID = 1629039933492350431L;
    private static final SpecificData MODEL$ = new SpecificData();
    private static final BinaryMessageEncoder<SpeedEventAvro> ENCODER =
            new BinaryMessageEncoder<>(MODEL$, SCHEMA$);
    private static final BinaryMessageDecoder<SpeedEventAvro> DECODER =
            new BinaryMessageDecoder<>(MODEL$, SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumWriter<SpeedEventAvro>
            WRITER$ = (org.apache.avro.io.DatumWriter<SpeedEventAvro>) MODEL$.createDatumWriter(SCHEMA$);
    @SuppressWarnings("unchecked")
    private static final org.apache.avro.io.DatumReader<SpeedEventAvro>
            READER$ = (org.apache.avro.io.DatumReader<SpeedEventAvro>) MODEL$.createDatumReader(SCHEMA$);
    private double speed;
    private double acceleration;

    /**
     * Default constructor.  Note that this does not initialize fields
     * to their default values from the schema.  If that is desired then
     * one should use <code>newBuilder()</code>.
     */
    public SpeedEventAvro() {
    }

    /**
     * All-args constructor.
     *
     * @param speed        The new value for speed
     * @param acceleration The new value for acceleration
     */
    public SpeedEventAvro(java.lang.Double speed, java.lang.Double acceleration) {
        this.speed = speed;
        this.acceleration = acceleration;
    }

    public static org.apache.avro.Schema getClassSchema() {
        return SCHEMA$;
    }

    /**
     * Return the BinaryMessageEncoder instance used by this class.
     *
     * @return the message encoder used by this class
     */
    public static BinaryMessageEncoder<SpeedEventAvro> getEncoder() {
        return ENCODER;
    }

    /**
     * Return the BinaryMessageDecoder instance used by this class.
     *
     * @return the message decoder used by this class
     */
    public static BinaryMessageDecoder<SpeedEventAvro> getDecoder() {
        return DECODER;
    }

    /**
     * Create a new BinaryMessageDecoder instance for this class that uses the specified {@link SchemaStore}.
     *
     * @param resolver a {@link SchemaStore} used to find schemas by fingerprint
     * @return a BinaryMessageDecoder instance for this class backed by the given SchemaStore
     */
    public static BinaryMessageDecoder<SpeedEventAvro> createDecoder(SchemaStore resolver) {
        return new BinaryMessageDecoder<>(MODEL$, SCHEMA$, resolver);
    }

    /**
     * Deserializes a SpeedEventAvro from a ByteBuffer.
     *
     * @param b a byte buffer holding serialized data for an instance of this class
     * @return a SpeedEventAvro instance decoded from the given buffer
     * @throws java.io.IOException if the given bytes could not be deserialized into an instance of this class
     */
    public static SpeedEventAvro fromByteBuffer(
            java.nio.ByteBuffer b) throws java.io.IOException {
        return DECODER.decode(b);
    }

    /**
     * Creates a new SpeedEventAvro RecordBuilder.
     *
     * @return A new SpeedEventAvro RecordBuilder
     */
    public static ru.practicum.avro_example.SpeedEventAvro.Builder newBuilder() {
        return new ru.practicum.avro_example.SpeedEventAvro.Builder();
    }

    /**
     * Creates a new SpeedEventAvro RecordBuilder by copying an existing Builder.
     *
     * @param other The existing builder to copy.
     * @return A new SpeedEventAvro RecordBuilder
     */
    public static ru.practicum.avro_example.SpeedEventAvro.Builder newBuilder(ru.practicum.avro_example.SpeedEventAvro.Builder other) {
        if (other == null) {
            return new ru.practicum.avro_example.SpeedEventAvro.Builder();
        } else {
            return new ru.practicum.avro_example.SpeedEventAvro.Builder(other);
        }
    }

    /**
     * Creates a new SpeedEventAvro RecordBuilder by copying an existing SpeedEventAvro instance.
     *
     * @param other The existing instance to copy.
     * @return A new SpeedEventAvro RecordBuilder
     */
    public static ru.practicum.avro_example.SpeedEventAvro.Builder newBuilder(ru.practicum.avro_example.SpeedEventAvro other) {
        if (other == null) {
            return new ru.practicum.avro_example.SpeedEventAvro.Builder();
        } else {
            return new ru.practicum.avro_example.SpeedEventAvro.Builder(other);
        }
    }

    /**
     * Serializes this SpeedEventAvro to a ByteBuffer.
     *
     * @return a buffer holding the serialized data for this instance
     * @throws java.io.IOException if this instance could not be serialized
     */
    public java.nio.ByteBuffer toByteBuffer() throws java.io.IOException {
        return ENCODER.encode(this);
    }

    @Override
    public org.apache.avro.specific.SpecificData getSpecificData() {
        return MODEL$;
    }

    @Override
    public org.apache.avro.Schema getSchema() {
        return SCHEMA$;
    }

    // Used by DatumWriter.  Applications should not call.
    @Override
    public java.lang.Object get(int field$) {
        switch (field$) {
            case 0:
                return speed;
            case 1:
                return acceleration;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    // Used by DatumReader.  Applications should not call.
    @Override
    @SuppressWarnings(value = "unchecked")
    public void put(int field$, java.lang.Object value$) {
        switch (field$) {
            case 0:
                speed = (java.lang.Double) value$;
                break;
            case 1:
                acceleration = (java.lang.Double) value$;
                break;
            default:
                throw new IndexOutOfBoundsException("Invalid index: " + field$);
        }
    }

    /**
     * Gets the value of the 'speed' field.
     *
     * @return The value of the 'speed' field.
     */
    public double getSpeed() {
        return speed;
    }

    /**
     * Sets the value of the 'speed' field.
     *
     * @param value the value to set.
     */
    public void setSpeed(double value) {
        this.speed = value;
    }

    /**
     * Gets the value of the 'acceleration' field.
     *
     * @return The value of the 'acceleration' field.
     */
    public double getAcceleration() {
        return acceleration;
    }

    /**
     * Sets the value of the 'acceleration' field.
     *
     * @param value the value to set.
     */
    public void setAcceleration(double value) {
        this.acceleration = value;
    }

    @Override
    public void writeExternal(java.io.ObjectOutput out)
            throws java.io.IOException {
        WRITER$.write(this, SpecificData.getEncoder(out));
    }

    @Override
    public void readExternal(java.io.ObjectInput in)
            throws java.io.IOException {
        READER$.read(this, SpecificData.getDecoder(in));
    }

    @Override
    protected boolean hasCustomCoders() {
        return true;
    }

    @Override
    public void customEncode(org.apache.avro.io.Encoder out)
            throws java.io.IOException {
        out.writeDouble(this.speed);

        out.writeDouble(this.acceleration);

    }

    @Override
    public void customDecode(org.apache.avro.io.ResolvingDecoder in)
            throws java.io.IOException {
        org.apache.avro.Schema.Field[] fieldOrder = in.readFieldOrderIfDiff();
        if (fieldOrder == null) {
            this.speed = in.readDouble();

            this.acceleration = in.readDouble();

        } else {
            for (int i = 0; i < 2; i++) {
                switch (fieldOrder[i].pos()) {
                    case 0:
                        this.speed = in.readDouble();
                        break;

                    case 1:
                        this.acceleration = in.readDouble();
                        break;

                    default:
                        throw new java.io.IOException("Corrupt ResolvingDecoder.");
                }
            }
        }
    }

    /**
     * RecordBuilder for SpeedEventAvro instances.
     */
    @org.apache.avro.specific.AvroGenerated
    public static class Builder extends org.apache.avro.specific.SpecificRecordBuilderBase<SpeedEventAvro>
            implements org.apache.avro.data.RecordBuilder<SpeedEventAvro> {

        private double speed;
        private double acceleration;

        /**
         * Creates a new Builder
         */
        private Builder() {
            super(SCHEMA$, MODEL$);
        }

        /**
         * Creates a Builder by copying an existing Builder.
         *
         * @param other The existing Builder to copy.
         */
        private Builder(ru.practicum.avro_example.SpeedEventAvro.Builder other) {
            super(other);
            if (isValidValue(fields()[0], other.speed)) {
                this.speed = data().deepCopy(fields()[0].schema(), other.speed);
                fieldSetFlags()[0] = other.fieldSetFlags()[0];
            }
            if (isValidValue(fields()[1], other.acceleration)) {
                this.acceleration = data().deepCopy(fields()[1].schema(), other.acceleration);
                fieldSetFlags()[1] = other.fieldSetFlags()[1];
            }
        }

        /**
         * Creates a Builder by copying an existing SpeedEventAvro instance
         *
         * @param other The existing instance to copy.
         */
        private Builder(ru.practicum.avro_example.SpeedEventAvro other) {
            super(SCHEMA$, MODEL$);
            if (isValidValue(fields()[0], other.speed)) {
                this.speed = data().deepCopy(fields()[0].schema(), other.speed);
                fieldSetFlags()[0] = true;
            }
            if (isValidValue(fields()[1], other.acceleration)) {
                this.acceleration = data().deepCopy(fields()[1].schema(), other.acceleration);
                fieldSetFlags()[1] = true;
            }
        }

        /**
         * Gets the value of the 'speed' field.
         *
         * @return The value.
         */
        public double getSpeed() {
            return speed;
        }


        /**
         * Sets the value of the 'speed' field.
         *
         * @param value The value of 'speed'.
         * @return This builder.
         */
        public ru.practicum.avro_example.SpeedEventAvro.Builder setSpeed(double value) {
            validate(fields()[0], value);
            this.speed = value;
            fieldSetFlags()[0] = true;
            return this;
        }

        /**
         * Checks whether the 'speed' field has been set.
         *
         * @return True if the 'speed' field has been set, false otherwise.
         */
        public boolean hasSpeed() {
            return fieldSetFlags()[0];
        }


        /**
         * Clears the value of the 'speed' field.
         *
         * @return This builder.
         */
        public ru.practicum.avro_example.SpeedEventAvro.Builder clearSpeed() {
            fieldSetFlags()[0] = false;
            return this;
        }

        /**
         * Gets the value of the 'acceleration' field.
         *
         * @return The value.
         */
        public double getAcceleration() {
            return acceleration;
        }


        /**
         * Sets the value of the 'acceleration' field.
         *
         * @param value The value of 'acceleration'.
         * @return This builder.
         */
        public ru.practicum.avro_example.SpeedEventAvro.Builder setAcceleration(double value) {
            validate(fields()[1], value);
            this.acceleration = value;
            fieldSetFlags()[1] = true;
            return this;
        }

        /**
         * Checks whether the 'acceleration' field has been set.
         *
         * @return True if the 'acceleration' field has been set, false otherwise.
         */
        public boolean hasAcceleration() {
            return fieldSetFlags()[1];
        }


        /**
         * Clears the value of the 'acceleration' field.
         *
         * @return This builder.
         */
        public ru.practicum.avro_example.SpeedEventAvro.Builder clearAcceleration() {
            fieldSetFlags()[1] = false;
            return this;
        }

        @Override
        @SuppressWarnings("unchecked")
        public SpeedEventAvro build() {
            try {
                SpeedEventAvro record = new SpeedEventAvro();
                record.speed = fieldSetFlags()[0] ? this.speed : (java.lang.Double) defaultValue(fields()[0]);
                record.acceleration = fieldSetFlags()[1] ? this.acceleration : (java.lang.Double) defaultValue(fields()[1]);
                return record;
            } catch (org.apache.avro.AvroMissingFieldException e) {
                throw e;
            } catch (java.lang.Exception e) {
                throw new org.apache.avro.AvroRuntimeException(e);
            }
        }
    }
}










